var sql1 = `
    SELECT LAST_NAME, SALARY
    FROM EMPLOYEE
    WHERE SALARY >= 12000`;

var sql2 = `
    SELECT LAST_NAME, DEPARTMENT_ID
    FROM EMPLOYEE
    WHERE EMPLOYEE_ID = '176'
`;

var sql3 = `
    SELECT LAST_NAME, SALARY
    FROM EMPLOYEE
    WHERE SALARY >= 5000 AND SALARY <=12000
`;

var sql4 = `
    SELECT LAST_NAME, JOB_ID, HIRE_DATE
    FROM EMPLOYEE
    WHERE HIRE_DATE >= '1998/02/20'
    AND HIRE_DATE <= '1998/05/01'
    ORDER BY HIRE_DATE
`;

var sql5 = `
    SELECT LAST_NAME, DEPARTMENT_ID
    FROM EMPLOYEE
    WHERE DEPARTMENT_ID = '50'
    AND DEPARTMENT_ID = '20'
`

var sql6 = `
    SELECT LAST_NAME, SALARY
    FROM EMPLOYEE
    WHERE SALARY >= 5000
    AND SALARY <=12000
    AND DEPARTMENT_ID = '20'
    OR DEPARTMENT_ID = '50'
`;

var sql7 = `
    SELECT LAST_NAME, HIRE_DATE
    FROM EMPLOYEE
    WHERE HIRE_DATE LIKE '1994%'
`;

var sql8 = `
    SELECT LAST_NAME, JOB_ID
    FROM EMPLOYEE
    WHERE IS NULL MANAGER_ID
`;
var sql9 = `
    SELECT LAST_NAME, SALARY, COMISSION_PCT
    FROM EMPLOYEE
    WHERE NOT NULL COMISSION_PCT
`;

var sql10 = `
    SELECT LAST_NAME
    FROM EMPLOYEE
    WHERE LAST_NAME LIKE '____a%'
`;

var sql11 = `
    SELECT LAST_NAME
    FROM EMPLOYEE
    WHERE LAST_NAME LIKE '%a%'
    OR LAST_NAME LIKE '%e%'
`;

var sql12 = `
    SELECT LAST_NAME, JOB_ID, SALARY
    FROM EMPLOYEE
    WHERE NOT IN (SELECT SALARY
                  FROM EMPLOYEE
                  WHERE SALARY <> 2500
                  AND SALARY <> 3500
                  AND SALARY <> 7000)
    AND IN (SELECT JOB_ID
            FROM EMPLOYEE
            WHERE JOB_ID = 'SA_REP'
            OR JOB_ID = 'ST_CLERK');
`

var sql13 = `
    SELECT JOB_
    FROM
    WHERE
`

var sql14 = `
    SELECT EMPLOYEE.LAST_NAME, EMPLOYEE.DEPARTMENT_ID, DEPARTMENT.DEPARTMENT_NAME
    FROM EMPLOYEE, DEPARTMENT
`

var sql15 = `
    SELECT DISTINCT EMPLOYEE.JOB_ID, LOCATION.LOCATION_ID
    FROM EMPLOYEE, LOCATION
    WHERE EMPLOYEE.ID = '30'
    OR EMPLOYEE.ID = '90'
`

var sql16 = `
    SELECT EMPLOYEE.LAST_NAME, DEPARTMENT.DEPARTMENT_NAME, LOCATION.LOCATION_ID, LOCATION.CITY
    FROM EMPLOYEE, DEPARTMENT
    WHERE NOT NULL EMPLOYEE.COMMISSION_PCT
`;

var sql17 = `
    SELECT LAST_NAME, HIRE_DATE
    FROM EMPLOYEE
    WHERE HIRE_DATE >= (SELECT HIRE_DATE
                        FROM EMPLOYEE
                        WHERE LAST_NAME = 'DAVIES')
`
